//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuzobot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conv()
        {
            this.Submits = new HashSet<Submit>();
        }
    
        public int Id { get; set; }
        public string ConversationId { get; set; }
        public string UserAddress { get; set; }
        public string BotAddress { get; set; }
        public string ChannelId { get; set; }
        public System.DateTime LastActive { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submit> Submits { get; set; }
    }
}
