//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuzobot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submit
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public int ConvId { get; set; }
        public int ContestId { get; set; }
        public Nullable<double> Score { get; set; }
        public bool IsNotAdult { get; set; }
        public bool IsWinner { get; set; }
        public string Promoceode { get; set; }
        public string UserName { get; set; }
    
        public virtual Conv Conv { get; set; }
        public virtual Contest Contest { get; set; }
    }
}
