//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuzobot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuzobotModelContainer : DbContext
    {
        public TuzobotModelContainer()
            : base("name=TuzobotModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conv> ConvSet { get; set; }
        public virtual DbSet<Contest> ContestSet { get; set; }
        public virtual DbSet<Submit> SubmitSet { get; set; }
    }
}
